### PR TITLE
Add schedule and prizes to info page

### PR DESCRIPTION
**Pull request by tfogo**
Need a lgtm

### CODE REVIEW

**Comment by nquinlan** [comment]
I think 2nd & 3rd place should probs have cool descriptions too

**Comment by nquinlan** [comment]
You should standardize the casing on the prize titles:

> SendGrid: Best use of SendGrid
> Twilio: Best Use of the Twilio API

**Comment by tfogo** [comment]
@nquinlan Yup.

**Comment by tfogo** [comment]
@nquinlan okay, took wanna take a look at that now?

**Comment by nquinlan** [comment]
Merged.

**Pull request merged**
